version: 2.1

jobs:
  Devop:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - run:
          name: Install Dependencies
          command: timeout 1m lscpu

  Devop1:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - run:
          name: Install Dependencies
          command: timeout 1m lscpu

  Devop2:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - run:
          name: Install Dependencies
          command: timeout 1m lscpu

  Devop3:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - run:
          name: Install Dependencies
          command: timeout 1m lscpu

  show_cpu_count:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - run:
          name: Show CPU Count
          command: nproc

workflows:
  build:
    jobs:
      - Devop
      - Devop1
      - Devop2
      - Devop3
      - show_cpu_count
